# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: ArchiveFiles@2
  displayName: 'Archive src directory'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'Az - R&D-EdgeLoginsFunction'
    appType: 'functionAppLinux'
    appName: 'rwedgelogins'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
